version: "3.7"

    services:
          mysqlsrv:
                image: mysql:8.0.37
                environment:
                      MYSQL_ROOT_PASSWORD: "123456"
                      MYSQL_DATABASE: "testedb"

                ports:
                  - "3306:3306"

                volumes:
                  - /data/mysql-A:/var/lib/mysql

                networks:
                  - minha-rede

          adminer:
            image: adminer
            ports:
              - 8080:8080
            networks:
              - minha-rede


      networks:
        minha-rede:
            driver: bridge
